# Auto-generated by k_sum_exists.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid
set logscale xy

$DATA_K3 << EOD
# n comparisons time n_pow_km1_logn
20 1900 0.000000000 1728.77
40 9360 0.000000000 8515.08
80 44240 0.000000000 40460.34
160 203520 0.001000000 187441.36
320 918720 0.001000000 852165.44
640 4089600 0.009000000 3818261.75
1280 18008320 0.038000000 16911446.99
EOD

$DATA_K4 << EOD
# n comparisons time n_pow_km1_logn
10 960 0.000000000 3321.93
15 3640 0.000000000 13185.76
20 11400 0.000000000 34575.42
30 40600 0.000000000 132486.05
45 170280 0.000000000 500445.11
65 611520 0.002000000 1653892.76
95 1937810 0.004000000 5632829.95
EOD

set output 'k3.png'
set title 'k=3: comparisons vs n (worst case, no valid triple exists)'
set xlabel 'n'
set ylabel 'comparisons'
plot $DATA_K3 using 1:2 with linespoints pt 7 lw 2 title 'measured (k=3)', \
     $DATA_K3 using 1:4 with lines dt 2 lw 1.5 lc rgb 'red' title 'n^2 log2(n) (theory)'

set output 'k4.png'
set title 'k=4: comparisons vs n (worst case, no valid quadruple exists)'
set xlabel 'n'
set ylabel 'comparisons'
plot $DATA_K4 using 1:2 with linespoints pt 7 lw 2 title 'measured (k=4)', \
     $DATA_K4 using 1:4 with lines dt 2 lw 1.5 lc rgb 'red' title 'n^3 log2(n) (theory)'
