/*
 * binary_vs_ternary.c
 *
 * Compares binary search (splits into 2 intervals) with ternary
 * search (splits into 3 intervals) on a sorted array of n elements.
 *
 * Theory:
 *   A k-ary search needs (k-1) comparisons per level to decide which
 *   of the k sub-intervals to recurse into, and needs log_k(n) levels.
 *   Total comparisons ~ (k-1) * log_k(n) = [(k-1)/log2(k)] * log2(n).
 *   f(k) = (k-1)/log2(k) is MINIMIZED at k=2 (f(2)=1) and increases
 *   for k>2 (f(3) = 2/log2(3) = 1.262), so binary search does the
 *   fewest comparisons among all k-ary search strategies.
 *
 * This program empirically counts the exact number of comparisons
 * each algorithm performs (worst case: searching for an absent key,
 * which forces the search all the way down to an interval of size 1)
 * across a range of array sizes n, and times both algorithms.
 * Results are written into a single self-contained GNUPLOT script
 * "plot.gnu" (data embedded inline -- no .csv/.dat/.py file).
 *
 * Compile:  gcc -O2 -o binary_vs_ternary binary_vs_ternary.c -lm
 * Run:      ./binary_vs_ternary
 * Plot:     gnuplot plot.gnu
 *           (produces comparisons.png, time.png, and ratio.png)
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <stdint.h>

/* ======================================================================
 *  BINARY SEARCH
 * ====================================================================== */
static int binary_search(const int *a, int n, int x, long long *cmp) {
    int lo = 0, hi = n - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        (*cmp)++;
        if (a[mid] == x) return mid;
        (*cmp)++;
        if (a[mid] < x) lo = mid + 1;
        else            hi = mid - 1;
    }
    return -1;
}

/* ======================================================================
 *  TERNARY SEARCH
 * ====================================================================== */
static int ternary_search(const int *a, int n, int x, long long *cmp) {
    int lo = 0, hi = n - 1;
    while (lo <= hi) {
        int third = (hi - lo) / 3;
        int mid1 = lo + third;
        int mid2 = hi - third;

        (*cmp)++;
        if (a[mid1] == x) return mid1;
        (*cmp)++;
        if (a[mid2] == x) return mid2;
        (*cmp)++;
        if (x < a[mid1]) {
            hi = mid1 - 1;
        } else {
            (*cmp)++;
            if (x > a[mid2]) lo = mid2 + 1;
            else { lo = mid1 + 1; hi = mid2 - 1; }
        }
    }
    return -1;
}

/* ======================================================================
 *  BENCHMARK HARNESS
 * ====================================================================== */
static double sec(clock_t a, clock_t b) { return (double)(b - a) / CLOCKS_PER_SEC; }

/* volatile sink to stop the optimizer from proving these read-only
 * calls have no observable effect and eliminating/hoisting them
 * (see discussion of this exact issue in earlier projects) */
static volatile long g_sink = 0;

static int trials_for(int n) {
    long t = 2000000L; /* fixed budget: log(n) is cheap, so we can
                           afford many repetitions even at huge n */
    (void)n;
    if (t > 2000000) t = 2000000;
    return (int)t;
}

int main(void) {
    int sizes[] = {1000, 4000, 16000, 64000, 256000, 1024000,
                   4096000, 16384000, 65536000};
    int nsizes = sizeof(sizes) / sizeof(sizes[0]);

    FILE *gp = fopen("plot.gnu", "w");
    if (!gp) { perror("fopen plot.gnu"); return 1; }
    fprintf(gp, "# Auto-generated by binary_vs_ternary.c\n");
    fprintf(gp, "# Run with:  gnuplot plot.gnu\n");
    fprintf(gp, "set terminal pngcairo size 900,650 enhanced font 'Arial,11'\n");
    fprintf(gp, "set grid\n\n");

    fprintf(gp, "$DATA << EOD\n");
    fprintf(gp, "# n binary_cmp ternary_cmp binary_time ternary_time ratio log2n\n");

    for (int s = 0; s < nsizes; s++) {
        int n = sizes[s];
        /* Sorted array of EVEN numbers 0,2,4,...,2n-2. Every search
         * key we probe is ODD, guaranteed absent, forcing the search
         * all the way down to an interval of size 1 -- the true
         * worst case for both algorithms. */
        int *a = malloc((size_t)n * sizeof(int));
        for (int i = 0; i < n; i++) a[i] = 2 * i;

        int T = trials_for(n);
        long long cmpB = 0, cmpT = 0;
        clock_t t0, t1;

        t0 = clock();
        for (int i = 0; i < T; i++) {
            int key = 2 * ((i * 2654435761u) % (unsigned)n) + 1; /* odd, pseudo-random */
            long long c = 0;
            int r = binary_search(a, n, key, &c);
            g_sink ^= (long)(intptr_t)r;
            cmpB += c;
        }
        t1 = clock();
        double timeB = sec(t0, t1) / T;
        double avgCmpB = (double)cmpB / T;

        t0 = clock();
        for (int i = 0; i < T; i++) {
            int key = 2 * ((i * 2654435761u) % (unsigned)n) + 1;
            long long c = 0;
            int r = ternary_search(a, n, key, &c);
            g_sink ^= (long)(intptr_t)r;
            cmpT += c;
        }
        t1 = clock();
        double timeT = sec(t0, t1) / T;
        double avgCmpT = (double)cmpT / T;

        double ratio = avgCmpT / avgCmpB;
        double log2n = log2((double)n);

        printf("n=%9d  binary: %.3f cmp (%.1f ns)   ternary: %.3f cmp (%.1f ns)   ratio(T/B)=%.4f\n",
               n, avgCmpB, timeB * 1e9, avgCmpT, timeT * 1e9, ratio);

        fprintf(gp, "%d %.6f %.6f %.9f %.9f %.6f %.6f\n",
                n, avgCmpB, avgCmpT, timeB, timeT, ratio, log2n);

        free(a);
    }
    fprintf(gp, "EOD\n\n");

    /* --- Plot 1: comparisons vs n --- */
    fprintf(gp,
        "set output 'comparisons.png'\n"
        "set title 'Binary vs Ternary Search: comparisons vs n (worst case)'\n"
        "set xlabel 'n (array size)'\n"
        "set ylabel 'average comparisons per search'\n"
        "set logscale x\n"
        "plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'Binary search', \\\n"
        "     $DATA using 1:3 with linespoints pt 5 lw 2 title 'Ternary search', \\\n"
        "     $DATA using 1:7 with lines dt 2 lw 1 lc rgb 'gray50' title 'log2(n) reference'\n\n");

    /* --- Plot 2: time vs n --- */
    fprintf(gp,
        "set output 'time.png'\n"
        "set title 'Binary vs Ternary Search: time per search vs n (worst case)'\n"
        "set xlabel 'n (array size)'\n"
        "set ylabel 'average time per search (seconds)'\n"
        "set logscale x\n"
        "plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'Binary search', \\\n"
        "     $DATA using 1:5 with linespoints pt 5 lw 2 title 'Ternary search'\n\n");

    /* --- Plot 3: ratio vs n (should flatten near 1.26) --- */
    fprintf(gp,
        "set output 'ratio.png'\n"
        "set title 'Ternary/Binary comparison ratio -- converges near 2/log2(3) = 1.262'\n"
        "set xlabel 'n (array size)'\n"
        "set ylabel 'ternary comparisons / binary comparisons'\n"
        "set logscale x\n"
        "set yrange [0.8:1.6]\n"
        "set arrow from graph 0, first 1.2618595 to graph 1, first 1.2618595 nohead dt 2 lc rgb 'red'\n"
        "plot $DATA using 1:6 with linespoints pt 7 lw 2 title 'measured ratio', \\\n"
        "     1.2618595 with lines dt 2 lw 1 lc rgb 'red' title '2/log2(3) (theory)'\n");

    fclose(gp);
    printf("\nWrote plot.gnu -- run 'gnuplot plot.gnu' to generate:\n");
    printf("  comparisons.png, time.png, ratio.png\n");
    return 0;
}
