/*
 * selection_sort.c
 *
 * Selection sort: repeatedly find the minimum of the unsorted suffix
 * and swap it into place. Runs for i = 1..n-1 (0-indexed: 0..n-2).
 *
 * Loop invariant: at the start of outer-loop iteration i, A[0..i-1]
 * holds the i smallest elements of the array, in sorted order (see
 * accompanying write-up for the full initialization / maintenance /
 * termination argument).
 *
 * Comparisons: always exactly n(n-1)/2, REGARDLESS of input order --
 * the inner loop has no early-exit, so best case = worst case =
 * Theta(n^2) for comparisons. Swaps DO vary with input order (0 in
 * the best case of an already-sorted array, up to n-1 otherwise),
 * but swaps don't dominate the asymptotic running time.
 *
 * This program sorts three input types (already sorted, reverse
 * sorted, random) for growing n, counts comparisons and swaps
 * separately for each, verifies correctness against a reference
 * sort, and writes a self-contained GNUPLOT script "plot.gnu" (data
 * embedded inline -- no .csv/.dat/.py file) validating that the
 * comparison curves for all three input types are identical and
 * match n(n-1)/2, while the swap counts differ.
 *
 * Compile:  gcc -O2 -o selection_sort selection_sort.c
 * Run:      ./selection_sort
 * Plot:     gnuplot plot.gnu   (produces comparisons.png and swaps.png)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ======================================================================
 *  SELECTION SORT  (0-indexed: outer loop i = 0 .. n-2)
 * ====================================================================== */
static void selection_sort(int *a, int n, long long *cmp, long long *swaps) {
    for (int i = 0; i < n - 1; i++) {
        int min = i;
        for (int j = i + 1; j < n; j++) {
            (*cmp)++;
            if (a[j] < a[min]) min = j;
        }
        if (min != i) {
            int t = a[i]; a[i] = a[min]; a[min] = t;
            (*swaps)++;
        }
    }
}

/* ======================================================================
 *  HELPERS
 * ====================================================================== */
static int cmp_int(const void *x, const void *y) { return (*(const int *)x - *(const int *)y); }

static int *make_array(int n, const char *kind, unsigned seed) {
    int *a = malloc((size_t)n * sizeof(int));
    if (strcmp(kind, "sorted") == 0) {
        for (int i = 0; i < n; i++) a[i] = i;
    } else if (strcmp(kind, "reverse") == 0) {
        for (int i = 0; i < n; i++) a[i] = n - i;
    } else { /* random */
        srand(seed);
        for (int i = 0; i < n; i++) a[i] = rand() % 1000000;
    }
    return a;
}

static int is_sorted(const int *a, int n) {
    for (int i = 1; i < n; i++) if (a[i - 1] > a[i]) return 0;
    return 1;
}

static void run_correctness_tests(void) {
    const char *kinds[] = {"sorted", "reverse", "random"};
    int fails = 0, total = 0;
    for (int n = 0; n <= 300; n++) {
        for (int k = 0; k < 3; k++) {
            int *a = make_array(n, kinds[k], (unsigned)(n * 97 + k));
            long long cmp = 0, sw = 0;
            selection_sort(a, n, &cmp, &sw);
            total++;
            if (!is_sorted(a, n)) { fails++; printf("FAIL: n=%d kind=%s not sorted\n", n, kinds[k]); }
            free(a);
        }
    }
    printf("Correctness: %d/%d trials passed (n = 0..300, sorted/reverse/random inputs)\n",
           total - fails, total);
}

int main(void) {
    run_correctness_tests();

    FILE *gp = fopen("plot.gnu", "w");
    if (!gp) { perror("fopen plot.gnu"); return 1; }
    fprintf(gp, "# Auto-generated by selection_sort.c\n");
    fprintf(gp, "# Run with:  gnuplot plot.gnu\n");
    fprintf(gp, "set terminal pngcairo size 900,650 enhanced font 'Arial,11'\n");
    fprintf(gp, "set grid\n\n");

    int sizes[] = {100, 200, 400, 800, 1600, 3200, 6400, 12800, 25600};
    int nsizes = sizeof(sizes) / sizeof(sizes[0]);
    const char *kinds[] = {"sorted", "reverse", "random"};

    fprintf(gp, "$DATA << EOD\n");
    fprintf(gp, "# n cmp_sorted cmp_reverse cmp_random swaps_sorted swaps_reverse swaps_random n_choose_2\n");

    printf("\n%-8s %-14s %-14s %-14s %-14s %-14s %-14s\n",
           "n", "cmp(sorted)", "cmp(reverse)", "cmp(random)", "swaps(sorted)", "swaps(reverse)", "swaps(random)");

    for (int s = 0; s < nsizes; s++) {
        int n = sizes[s];
        long long cmpVals[3], swapVals[3];

        for (int k = 0; k < 3; k++) {
            int *a = make_array(n, kinds[k], (unsigned)(5000000u + n * 13u + k));
            long long cmp = 0, sw = 0;
            selection_sort(a, n, &cmp, &sw);
            cmpVals[k] = cmp; swapVals[k] = sw;
            free(a);
        }

        double nChoose2 = (double)n * (n - 1) / 2.0;

        printf("%-8d %-14lld %-14lld %-14lld %-14lld %-14lld %-14lld\n",
               n, cmpVals[0], cmpVals[1], cmpVals[2], swapVals[0], swapVals[1], swapVals[2]);
        fprintf(gp, "%d %lld %lld %lld %lld %lld %lld %.1f\n",
                n, cmpVals[0], cmpVals[1], cmpVals[2], swapVals[0], swapVals[1], swapVals[2], nChoose2);
    }
    fprintf(gp, "EOD\n\n");

    /* --- Plot 1: comparisons vs n -- all three input types should be IDENTICAL --- */
    fprintf(gp,
        "set output 'comparisons.png'\n"
        "set title 'Selection sort comparisons: identical for sorted/reverse/random input (no best case)'\n"
        "set xlabel 'n (array size)'\n"
        "set ylabel 'number of comparisons'\n"
        "plot $DATA using 1:2 with points pt 7 ps 2   title 'already sorted', \\\n"
        "     $DATA using 1:3 with points pt 6 ps 1.4 title 'reverse sorted', \\\n"
        "     $DATA using 1:4 with points pt 4 ps 0.8 title 'random', \\\n"
        "     $DATA using 1:8 with lines dt 2 lw 1.5 lc rgb 'red' title 'n(n-1)/2 (theory)'\n\n");

    /* --- Plot 2: swaps vs n -- these DO differ by input type --- */
    fprintf(gp,
        "set output 'swaps.png'\n"
        "set title 'Selection sort swaps: DOES vary by input arrangement'\n"
        "set xlabel 'n (array size)'\n"
        "set ylabel 'number of swaps'\n"
        "plot $DATA using 1:5 with linespoints pt 7 lw 2 title 'already sorted', \\\n"
        "     $DATA using 1:6 with linespoints pt 5 lw 2 title 'reverse sorted', \\\n"
        "     $DATA using 1:7 with linespoints pt 9 lw 2 title 'random'\n");

    fclose(gp);
    printf("\nWrote plot.gnu -- run 'gnuplot plot.gnu' to generate comparisons.png and swaps.png\n");
    return 0;
}
