# Auto-generated by merge_intervals.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid

$DATA << EOD
# n fast_cmp naive_cmp fast_time naive_time n_log2n n_squared
50 315 327 0.000000000 0.000000000 282.19 2500.00
100 776 1834 0.000000000 0.001000000 664.39 10000.00
200 1793 7242 0.000000000 0.000000000 1528.77 40000.00
400 3746 31327 0.000000000 0.000000000 3457.54 160000.00
800 9118 128429 0.000000000 0.000000000 7715.08 640000.00
1600 19580 573903 0.001000000 0.002000000 17030.17 2560000.00
3200 43385 2237499 0.000000000 0.006000000 37260.34 10240000.00
EOD

set output 'comparisons.png'
set title 'Merge intervals: O(n log n) sort-based vs O(n^2) naive repeated-pass'
set xlabel 'n (number of intervals)'
set ylabel 'comparisons'
set logscale xy
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'sort-based (measured)', \
     $DATA using 1:3 with linespoints pt 5 lw 2 title 'naive repeated-pass (measured)', \
     $DATA using 1:6 with lines dt 2 lw 1.5 lc rgb 'red'  title 'n log2(n) (theory)', \
     $DATA using 1:7 with lines dt 2 lw 1.5 lc rgb 'blue' title 'n^2 (theory)'

set output 'time.png'
set title 'Merge intervals: time vs n'
set xlabel 'n (number of intervals)'
set ylabel 'time (seconds)'
set logscale xy
plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'sort-based O(n log n)', \
     $DATA using 1:5 with linespoints pt 5 lw 2 title 'naive repeated-pass'
