# Auto-generated by q1.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid

$DATA << EOD
# n ops_countsort time_countsort time_qsort n_reference
1000 2000 0.000000000 0.000000000 1000
5000 10000 0.000000000 0.000000000 5000
10000 20000 0.000000000 0.000000000 10000
50000 100000 0.001000000 0.000000000 50000
100000 200000 0.000000000 0.002000000 100000
500000 1000000 0.002000000 0.009000000 500000
1000000 2000000 0.008000000 0.016000000 1000000
2000000 4000000 0.016000000 0.045000000 2000000
5000000 10000000 0.038000000 0.081000000 5000000
EOD

set output 'ops.png'
set title 'O(n) counting sort by color: array operations vs n'
set xlabel 'n'
set ylabel 'array reads/writes'
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'measured operations', \
     $DATA using ($1):(2*$1) with lines dt 2 lw 1.5 lc rgb 'red' title '2n (theory)'

set output 'time.png'
set title 'O(n) counting sort vs O(n log n) qsort: time vs n'
set xlabel 'n'
set ylabel 'time (seconds)'
set logscale xy
plot $DATA using 1:3 with linespoints pt 7 lw 2 title 'counting sort O(n)', \
     $DATA using 1:4 with linespoints pt 5 lw 2 title 'qsort O(n log n)'
