# Auto-generated by pair_sum_exists.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid

$DATA << EOD
# n nlogn_cmp brute_cmp nlogn_time brute_time n_log2n n_squared
100 1400 10000 0.000000000 0.000000000 664.39 10000.00
200 3200 40000 0.000000000 0.000000000 1528.77 40000.00
400 7200 160000 0.000000000 0.000000000 3457.54 160000.00
800 16000 640000 0.000000000 0.002000000 7715.08 640000.00
1600 35200 2560000 0.000000000 0.004000000 17030.17 2560000.00
3200 76800 10240000 0.000000000 0.018000000 37260.34 10240000.00
6400 166400 40960000 0.001000000 0.071000000 80920.68 40960000.00
12800 358400 163840000 0.003000000 0.286000000 174641.36 163840000.00
25600 768000 655360000 0.004000000 1.145000000 374882.72 655360000.00
EOD

set output 'comparisons.png'
set title 'Pair-sum-exists: O(n log n) binary-search method vs O(n^2) brute force'
set xlabel 'n'
set ylabel 'comparisons'
set logscale xy
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'O(n log n) method (measured)', \
     $DATA using 1:3 with linespoints pt 5 lw 2 title 'O(n^2) brute force (measured)', \
     $DATA using 1:6 with lines dt 2 lw 1.5 lc rgb 'red'  title 'n log2(n) (theory)', \
     $DATA using 1:7 with lines dt 2 lw 1.5 lc rgb 'blue' title 'n^2 (theory)'

set output 'time.png'
set title 'Pair-sum-exists: time vs n'
set xlabel 'n'
set ylabel 'time (seconds)'
set logscale xy
plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'O(n log n) method', \
     $DATA using 1:5 with linespoints pt 5 lw 2 title 'O(n^2) brute force'
