# Auto-generated by party_max_overlap.c
# Run with:  gnuplot plot.gnu
set terminal pngcairo size 900,650 enhanced font 'Arial,11'
set grid

$DATA << EOD
# n sweep_cmp brute_cmp sweep_time brute_time n_log2n n_squared
50 736 2500 0.000000000 0.000000000 664.39 2500.00
100 1671 10000 0.000000000 0.000000000 1528.77 10000.00
200 4071 40000 0.000000000 0.001000000 3457.54 40000.00
400 8991 160000 0.000000000 0.001000000 7715.08 160000.00
800 20018 640000 0.000000000 0.002000000 17030.17 640000.00
1600 43106 2560000 0.000000000 0.010000000 37260.34 2560000.00
3200 97785 10240000 0.002000000 0.049000000 80920.68 10240000.00
6400 200522 40960000 0.001000000 0.179000000 174641.36 40960000.00
12800 449737 163840000 0.004000000 0.725000000 374882.72 163840000.00
EOD

set output 'comparisons.png'
set title 'Max overlap: O(n log n) sweep line vs O(n^2) brute force'
set xlabel 'n (number of people)'
set ylabel 'comparisons'
set logscale xy
plot $DATA using 1:2 with linespoints pt 7 lw 2 title 'sweep line (measured)', \
     $DATA using 1:3 with linespoints pt 5 lw 2 title 'brute force (measured)', \
     $DATA using 1:6 with lines dt 2 lw 1.5 lc rgb 'red'  title '2n log2(2n) (theory)', \
     $DATA using 1:7 with lines dt 2 lw 1.5 lc rgb 'blue' title 'n^2 (theory)'

set output 'time.png'
set title 'Max overlap: time vs n'
set xlabel 'n (number of people)'
set ylabel 'time (seconds)'
set logscale xy
plot $DATA using 1:4 with linespoints pt 7 lw 2 title 'sweep line O(n log n)', \
     $DATA using 1:5 with linespoints pt 5 lw 2 title 'brute force O(n^2)'
